blueprint:
  name: flashing lights
  description: >
     Flashing lights via on off and delay and finally restore the previous light states.
  domain: automation
  source_url: https://github.com/cloudishBenne/home-assistant_blueprints/blob/main/flashing_lights.yaml
  input:
    activated:
        name: Sensor
        description: "Sensor to activate or deactivate flashing lights."
        selector:
            entity:
    target_state:
        name: Sensorstate
        description: "Sensorstate to be used"
        text:
    target_lights:
        name: Lights
        description: "To using lights"
        selector:
          target:
            entity:
              domain: light
    target_scene:
        name: Scene
        description: "To using scene"
        selector:
          target:
            entity:
              domain: scene
    delay:
      name: (OPTIONAL) Delay
      description: "Delay flashing lights"
      default: 1000
      selector:
        number:
          min: 0
          max: 20000
          unit_of_measurement: milliseconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input activated
    to: !input target_state

variables:
  activated: !input activated
  target_state: !input target_state
  delay: !input delay
  target_lights: !input target_lights
  target_scene: !input target_scene

condition: []

action:
  - service: scene.create
    data:
        scene_id: all_lights_snapshot
        snapshot_entities: >
               {% set lights = states.light
                 | map(attribute='entity_id') | join(',') %}
                 {{lights}}
  - service: light.turn_off
    target: !input target_lights
  - repeat:
      while:
      - condition: template
        value_template: "{{ is_state(activated, target_state) }}"
      sequence:
      - service: scene.turn_on
        target: !input target_scene
      - delay: 
          milliseconds: "{{ delay }}"
      - service: light.turn_off
        target: !input target_lights
      - delay: 
          milliseconds: "{{ delay }}"
  - service: scene.turn_on
    data:
      entity_id: scene.all_lights_snapshot
